// ============================================================================
// RipeSpot — Demo Mode Data
// ============================================================================
// Realistic mock proposals, compliance checks, and QAP scores used when
// NEXT_PUBLIC_DEMO_MODE=true. Allows customer demos without a live backend.
// ============================================================================

// ---- Proposal list items (dashboard view) ----------------------------------

export const DEMO_PROPOSALS = [
  {
    id: "demo-p1",
    proposal_number: "CP-2025-0041",
    project_name: "Live Oak Senior Residences",
    developer_entity: "Horizon Affordable Housing Partners, LLC",
    developer_contact_name: "Maria Gutierrez",
    developer_contact_email: "m.gutierrez@horizonhousing.com",
    credit_type: "lihtc_9pct",
    status: "in_review",
    total_units: 72,
    affordable_units: 72,
    ami_30_pct_units: 8,
    ami_50_pct_units: 36,
    ami_60_pct_units: 28,
    ami_80_pct_units: 0,
    total_development_cost: 18400000,
    eligible_basis: 15200000,
    qualified_basis: 15200000,
    annual_credit_amount: 1012400,
    tax_credit_equity: 9314080,
    credit_price: 0.92,
    bond_amount: null,
    permanent_loan_amount: 5800000,
    permanent_loan_rate: 0.0425,
    permanent_loan_term: 35,
    dscr: 1.28,
    developer_fee: 2281600,
    developer_fee_pct: 0.124,
    deferred_developer_fee: 750000,
    is_qct: true,
    is_dda: false,
    set_aside_election: "40_60",
    is_new_construction: true,
    is_rehab: false,
    project_address: "1421 Live Oak Street",
    city: "Houston",
    county: "Harris",
    state: "TX",
    qap_state: "TX",
    qap_year: 2025,
    compliance_score: 89,
    preliminary_qap_score: 72,
    max_qap_score: 105,
    ai_analysis_completed: true,
    ai_model_used: "claude-sonnet-4-6",
    ai_analysis_timestamp: "2025-03-18T14:23:11Z",
    submitted_at: "2025-03-15T09:00:00Z",
    updated_at: "2025-03-18T14:23:11Z",
  },
  {
    id: "demo-p2",
    proposal_number: "CP-2025-0038",
    project_name: "Magnolia Courts",
    developer_entity: "Gulf South Community Housing, Inc.",
    developer_contact_name: "James Thibodaux",
    developer_contact_email: "j.thibodaux@gulfsouthhousing.org",
    credit_type: "lihtc_4pct",
    status: "approved",
    total_units: 120,
    affordable_units: 120,
    ami_30_pct_units: 18,
    ami_50_pct_units: 54,
    ami_60_pct_units: 48,
    ami_80_pct_units: 0,
    total_development_cost: 31200000,
    eligible_basis: 22800000,
    qualified_basis: 22800000,
    annual_credit_amount: 912000,
    tax_credit_equity: 8299200,
    credit_price: 0.91,
    bond_amount: 20500000,
    permanent_loan_amount: 18200000,
    permanent_loan_rate: 0.0398,
    permanent_loan_term: 40,
    dscr: 1.19,
    developer_fee: 3494400,
    developer_fee_pct: 0.112,
    deferred_developer_fee: 400000,
    is_qct: false,
    is_dda: false,
    set_aside_election: "40_60",
    is_new_construction: true,
    is_rehab: false,
    project_address: "800 Magnolia Boulevard",
    city: "New Orleans",
    county: "Orleans",
    state: "LA",
    qap_state: "LA",
    qap_year: 2025,
    compliance_score: 94,
    preliminary_qap_score: 68,
    max_qap_score: 90,
    ai_analysis_completed: true,
    ai_model_used: "claude-sonnet-4-6",
    ai_analysis_timestamp: "2025-03-08T10:47:22Z",
    submitted_at: "2025-03-04T11:30:00Z",
    updated_at: "2025-03-08T10:47:22Z",
  },
  {
    id: "demo-p3",
    proposal_number: "CP-2025-0035",
    project_name: "River Bend Commons",
    developer_entity: "Austin Community Development Corp.",
    developer_contact_name: "Patricia Nguyen",
    developer_contact_email: "p.nguyen@austincdc.org",
    credit_type: "home",
    status: "deficiency",
    total_units: 48,
    affordable_units: 48,
    ami_30_pct_units: 0,
    ami_50_pct_units: 18,
    ami_60_pct_units: 30,
    ami_80_pct_units: 0,
    total_development_cost: 9800000,
    eligible_basis: null,
    qualified_basis: null,
    annual_credit_amount: null,
    tax_credit_equity: null,
    credit_price: null,
    bond_amount: null,
    permanent_loan_amount: 4200000,
    permanent_loan_rate: 0.0512,
    permanent_loan_term: 30,
    dscr: 1.09,
    developer_fee: 1078000,
    developer_fee_pct: 0.11,
    deferred_developer_fee: 0,
    is_qct: false,
    is_dda: false,
    set_aside_election: "not_applicable",
    is_new_construction: true,
    is_rehab: false,
    project_address: "3312 River Bend Drive",
    city: "Austin",
    county: "Travis",
    state: "TX",
    qap_state: null,
    qap_year: null,
    compliance_score: 58,
    preliminary_qap_score: null,
    max_qap_score: null,
    ai_analysis_completed: true,
    ai_model_used: "claude-sonnet-4-6",
    ai_analysis_timestamp: "2025-02-28T16:02:44Z",
    submitted_at: "2025-02-24T08:15:00Z",
    updated_at: "2025-02-28T16:02:44Z",
  },
  {
    id: "demo-p4",
    proposal_number: "CP-2025-0044",
    project_name: "Sunrise Pines Family Housing",
    developer_entity: "Lone Star Affordable Homes, LLC",
    developer_contact_name: "Derek Castillo",
    developer_contact_email: "d.castillo@lonestarhousing.com",
    credit_type: "lihtc_9pct",
    status: "received",
    total_units: 84,
    affordable_units: 84,
    ami_30_pct_units: 12,
    ami_50_pct_units: 42,
    ami_60_pct_units: 30,
    ami_80_pct_units: 0,
    total_development_cost: 22100000,
    eligible_basis: null,
    qualified_basis: null,
    annual_credit_amount: null,
    tax_credit_equity: null,
    credit_price: 0.935,
    bond_amount: null,
    permanent_loan_amount: 7200000,
    permanent_loan_rate: 0.0441,
    permanent_loan_term: 35,
    dscr: 1.22,
    developer_fee: 2652000,
    developer_fee_pct: 0.12,
    deferred_developer_fee: 900000,
    is_qct: false,
    is_dda: true,
    set_aside_election: "40_60",
    is_new_construction: true,
    is_rehab: false,
    project_address: "5500 Sunrise Boulevard",
    city: "San Antonio",
    county: "Bexar",
    state: "TX",
    qap_state: "TX",
    qap_year: 2025,
    compliance_score: null,
    preliminary_qap_score: null,
    max_qap_score: null,
    ai_analysis_completed: false,
    ai_model_used: null,
    ai_analysis_timestamp: null,
    submitted_at: "2025-03-28T13:45:00Z",
    updated_at: "2025-03-28T13:45:00Z",
  },
  {
    id: "demo-p5",
    proposal_number: "CP-2025-0029",
    project_name: "Cedar Ridge Apartments",
    developer_entity: "Bayou State Development Group, LLC",
    developer_contact_name: "Antoine Broussard",
    developer_contact_email: "a.broussard@bayoustate.com",
    credit_type: "lihtc_4pct",
    status: "denied",
    total_units: 96,
    affordable_units: 96,
    ami_30_pct_units: 0,
    ami_50_pct_units: 48,
    ami_60_pct_units: 48,
    ami_80_pct_units: 0,
    total_development_cost: 27800000,
    eligible_basis: 21400000,
    qualified_basis: 21400000,
    annual_credit_amount: 856000,
    tax_credit_equity: 6762400,
    credit_price: 0.79,
    bond_amount: 11200000,
    permanent_loan_amount: 14800000,
    permanent_loan_rate: 0.0558,
    permanent_loan_term: 35,
    dscr: 1.04,
    developer_fee: 5587800,
    developer_fee_pct: 0.201,
    deferred_developer_fee: 2100000,
    is_qct: true,
    is_dda: true,
    set_aside_election: "income_average",
    is_new_construction: true,
    is_rehab: false,
    project_address: "2244 Cedar Ridge Lane",
    city: "Baton Rouge",
    county: "East Baton Rouge",
    state: "LA",
    qap_state: "LA",
    qap_year: 2025,
    compliance_score: 41,
    preliminary_qap_score: 31,
    max_qap_score: 90,
    ai_analysis_completed: true,
    ai_model_used: "claude-sonnet-4-6",
    ai_analysis_timestamp: "2025-02-14T09:30:05Z",
    submitted_at: "2025-02-10T10:00:00Z",
    updated_at: "2025-02-14T09:30:05Z",
  },
];

// ---- Dashboard stats -------------------------------------------------------

export const DEMO_STATS = {
  total_proposals: 5,
  in_review: 1,
  approved: 1,
  denied: 1,
  deficiency: 1,
  received: 1,
  processing: 0,
  avg_compliance_score: 70,
  total_units_in_pipeline: 420,
};

// ---- Compliance checks by proposal ID -------------------------------------

export const DEMO_COMPLIANCE_CHECKS: Record<string, object[]> = {
  "demo-p1": [
    {
      id: "cc-p1-01", proposal_id: "demo-p1", sort_order: 1,
      check_name: "Set-Aside Election Compliance",
      category: "section_42", result: "pass", severity: "critical",
      regulatory_citation: "IRC §42(g)(1)",
      finding_detail: "Project correctly elects the 40/60 set-aside. All 72 units (100%) are restricted at or below 60% AMI, which satisfies and exceeds the 40% minimum threshold.",
      expected_value: "≥40% of units at ≤60% AMI", actual_value: "100% (72/72 units)",
      recommendation: null, created_at: "2025-03-18T14:23:11Z",
    },
    {
      id: "cc-p1-02", proposal_id: "demo-p1", sort_order: 2,
      check_name: "Income Targeting Verification",
      category: "section_42", result: "pass", severity: "critical",
      regulatory_citation: "IRC §42(g)(2)",
      finding_detail: "AMI unit breakdown is internally consistent: 8 units at 30% AMI (11.1%), 36 units at 50% AMI (50%), 28 units at 60% AMI (38.9%). Totals agree. No fair housing clustering concerns identified — income levels are distributed proportionally across unit types.",
      expected_value: "Unit counts sum to total affordable units", actual_value: "8+36+28 = 72 ✓",
      recommendation: null, created_at: "2025-03-18T14:23:11Z",
    },
    {
      id: "cc-p1-03", proposal_id: "demo-p1", sort_order: 3,
      check_name: "Eligible Basis — QCT Boost Verification",
      category: "section_42", result: "needs_review", severity: "warning",
      regulatory_citation: "IRC §42(d)(5)(B)",
      finding_detail: "Project claims the 130% QCT basis boost, which would increase eligible basis by $3,040,000. The QCT designation for Census Tract 1234.01 (Harris County) should be independently verified against HUD's current published QCT list before credit allocation.",
      expected_value: "HUD-confirmed QCT designation", actual_value: "Claimed but not verified in submission",
      recommendation: "Provide HUD QCT designation confirmation for Census Tract 1234.01 or remove the 130% boost from the eligible basis calculation.", created_at: "2025-03-18T14:23:11Z",
    },
    {
      id: "cc-p1-04", proposal_id: "demo-p1", sort_order: 4,
      check_name: "Applicable Fraction Calculation",
      category: "section_42", result: "pass", severity: "warning",
      regulatory_citation: "IRC §42(c)(1)",
      finding_detail: "100% of units are low-income restricted. Applicable fraction = 1.000. Qualified basis equals eligible basis of $15,200,000.",
      expected_value: "Applicable fraction ≤ 1.000", actual_value: "1.000 (72/72 units restricted)",
      recommendation: null, created_at: "2025-03-18T14:23:11Z",
    },
    {
      id: "cc-p1-05", proposal_id: "demo-p1", sort_order: 5,
      check_name: "Annual Credit Amount Verification",
      category: "section_42", result: "pass", severity: "warning",
      regulatory_citation: "IRC §42(a)",
      finding_detail: "Annual credit of $1,012,400 is correctly computed as $15,200,000 qualified basis × 9% (HERA-fixed applicable percentage for new construction 9% allocation). 10-year credit period produces $10,124,000 aggregate credits.",
      expected_value: "QB × 9% applicable percentage", actual_value: "$1,012,400/year ✓",
      recommendation: null, created_at: "2025-03-18T14:23:11Z",
    },
    {
      id: "cc-p1-06", proposal_id: "demo-p1", sort_order: 6,
      check_name: "Placed-in-Service Timeline",
      category: "section_42", result: "pass", severity: "informational",
      regulatory_citation: "IRC §42(e)(1)",
      finding_detail: "Construction is scheduled to complete Q3 2026, within the 2-year PIS window following an anticipated 2025 TDHCA allocation. No timeline risk identified based on current projections.",
      expected_value: "PIS by Dec 31, 2027 (end of year 2 post-allocation)", actual_value: "Projected Q3 2026 ✓",
      recommendation: null, created_at: "2025-03-18T14:23:11Z",
    },
    {
      id: "cc-p1-07", proposal_id: "demo-p1", sort_order: 7,
      check_name: "Developer Fee Reasonableness",
      category: "financial", result: "pass", severity: "warning",
      regulatory_citation: "TDHCA 2025 QAP §11.9(d)",
      finding_detail: "Developer fee of $2,281,600 represents 12.4% of TDC, within the 15% TDHCA standard. Deferred developer fee of $750,000 represents 32.9% of total developer fee and appears repayable from projected operations.",
      expected_value: "≤15% of TDC", actual_value: "12.4% ($2,281,600)",
      recommendation: null, created_at: "2025-03-18T14:23:11Z",
    },
    {
      id: "cc-p1-08", proposal_id: "demo-p1", sort_order: 8,
      check_name: "Debt Service Coverage Ratio",
      category: "financial", result: "pass", severity: "critical",
      regulatory_citation: "HUD Underwriting Guidelines §3.1.3",
      finding_detail: "DSCR of 1.28x exceeds the 1.15x minimum threshold required by most lenders and HFAs. The 13-point cushion above minimum provides adequate protection against moderate operating cost increases.",
      expected_value: "≥1.15x DSCR", actual_value: "1.28x ✓",
      recommendation: null, created_at: "2025-03-18T14:23:11Z",
    },
    {
      id: "cc-p1-09", proposal_id: "demo-p1", sort_order: 9,
      check_name: "Sources and Uses Balance",
      category: "financial", result: "pass", severity: "critical",
      regulatory_citation: "HUD CPD Notice 98-01",
      finding_detail: "Total sources equal total uses at $18,400,000. No funding gap identified. Sources composition: tax credit equity (50.6%), permanent debt (31.5%), deferred developer fee (4.1%), other soft sources (13.8%).",
      expected_value: "Sources = Uses (zero gap)", actual_value: "$18,400,000 = $18,400,000 ✓",
      recommendation: null, created_at: "2025-03-18T14:23:11Z",
    },
    {
      id: "cc-p1-10", proposal_id: "demo-p1", sort_order: 10,
      check_name: "HUD Total Development Cost Limits",
      category: "financial", result: "fail", severity: "warning",
      regulatory_citation: "HUD Notice H-2024-10 (TDC/HCC Limits)",
      finding_detail: "Per-unit TDC of $255,556 exceeds HUD's published TDC limit of $236,000 for the Houston MSA (elevator-type construction, 2025 limits). This overage may affect eligible basis in HOME-layered or HUD-assisted deals and should be documented with a cost reasonableness justification.",
      expected_value: "≤$236,000/unit (Houston MSA, elevator)", actual_value: "$255,556/unit",
      recommendation: "Prepare a cost reasonableness narrative citing local labor costs, energy code compliance requirements, and comparable comps. If HOME layering is anticipated, address directly in the underwriting narrative.", created_at: "2025-03-18T14:23:11Z",
    },
  ],

  "demo-p2": [
    {
      id: "cc-p2-01", proposal_id: "demo-p2", sort_order: 1,
      check_name: "Set-Aside Election Compliance",
      category: "section_42", result: "pass", severity: "critical",
      regulatory_citation: "IRC §42(g)(1)",
      finding_detail: "40/60 election properly structured. 100% of 120 units restricted at or below 60% AMI — well above the 40% minimum.",
      expected_value: "≥40% of units at ≤60% AMI", actual_value: "100% (120/120 units)",
      recommendation: null, created_at: "2025-03-08T10:47:22Z",
    },
    {
      id: "cc-p2-02", proposal_id: "demo-p2", sort_order: 2,
      check_name: "Income Targeting Verification",
      category: "section_42", result: "pass", severity: "critical",
      regulatory_citation: "IRC §42(g)(2)",
      finding_detail: "Unit mix is internally consistent: 18 units at 30% AMI (15%), 54 units at 50% AMI (45%), 48 units at 60% AMI (40%). Total 120 affordable units. Deep targeting at 30% AMI is a competitive strength.",
      expected_value: "Unit counts sum to total", actual_value: "18+54+48 = 120 ✓",
      recommendation: null, created_at: "2025-03-08T10:47:22Z",
    },
    {
      id: "cc-p2-03", proposal_id: "demo-p2", sort_order: 3,
      check_name: "25% Bond Test (4% Credit Eligibility)",
      category: "section_42", result: "pass", severity: "critical",
      regulatory_citation: "IRC §42(h)(4)(B)",
      finding_detail: "Bond amount of $20,500,000 represents 65.7% of TDC ($31,200,000). This comfortably exceeds the 50% threshold required to qualify the project for 4% tax credits without a competitive allocation.",
      expected_value: "Bond ≥ 50% of aggregate basis", actual_value: "65.7% ($20.5M / $31.2M) ✓",
      recommendation: null, created_at: "2025-03-08T10:47:22Z",
    },
    {
      id: "cc-p2-04", proposal_id: "demo-p2", sort_order: 4,
      check_name: "Eligible Basis Calculation",
      category: "section_42", result: "pass", severity: "warning",
      regulatory_citation: "IRC §42(d)",
      finding_detail: "No QCT or DDA boost claimed. Eligible basis of $22,800,000 is reasonable relative to TDC and consistent with a 100% affordable project excluding land and non-depreciable items.",
      expected_value: "Eligible basis ≤ TDC minus land/non-eligible", actual_value: "$22,800,000 (73.1% of TDC) ✓",
      recommendation: null, created_at: "2025-03-08T10:47:22Z",
    },
    {
      id: "cc-p2-05", proposal_id: "demo-p2", sort_order: 5,
      check_name: "Developer Fee Reasonableness",
      category: "financial", result: "pass", severity: "warning",
      regulatory_citation: "LHC 2025 QAP §10.4",
      finding_detail: "Developer fee of $3,494,400 represents 11.2% of TDC, well within the 15% LHC standard.",
      expected_value: "≤15% of TDC", actual_value: "11.2% ($3,494,400) ✓",
      recommendation: null, created_at: "2025-03-08T10:47:22Z",
    },
    {
      id: "cc-p2-06", proposal_id: "demo-p2", sort_order: 6,
      check_name: "Debt Service Coverage Ratio",
      category: "financial", result: "needs_review", severity: "warning",
      regulatory_citation: "HUD Underwriting Guidelines §3.1.3",
      finding_detail: "DSCR of 1.19x meets the 1.15x minimum threshold but leaves a narrow 4-point cushion. A 5% increase in operating expenses would compress DSCR to approximately 1.13x, below minimums.",
      expected_value: "≥1.15x DSCR", actual_value: "1.19x (marginal)",
      recommendation: "Stress-test the pro forma at +10% operating expenses and -5% gross potential income. Consider increasing reserves or reducing debt load if stress scenario falls below 1.10x.", created_at: "2025-03-08T10:47:22Z",
    },
    {
      id: "cc-p2-07", proposal_id: "demo-p2", sort_order: 7,
      check_name: "Sources and Uses Balance",
      category: "financial", result: "pass", severity: "critical",
      regulatory_citation: "HUD CPD Notice 98-01",
      finding_detail: "Sources equal uses at $31,200,000. Balanced financing structure with tax-exempt bond debt as primary source.",
      expected_value: "Sources = Uses", actual_value: "$31,200,000 = $31,200,000 ✓",
      recommendation: null, created_at: "2025-03-08T10:47:22Z",
    },
    {
      id: "cc-p2-08", proposal_id: "demo-p2", sort_order: 8,
      check_name: "Credit Pricing Verification",
      category: "financial", result: "pass", severity: "informational",
      regulatory_citation: "Market Standard",
      finding_detail: "Tax credit equity price of $0.91 per credit dollar is within the current market range of $0.85–$0.98. Consistent with 4% credit market pricing in the Gulf South region.",
      expected_value: "$0.85–$0.98/credit dollar", actual_value: "$0.91 ✓",
      recommendation: null, created_at: "2025-03-08T10:47:22Z",
    },
    {
      id: "cc-p2-09", proposal_id: "demo-p2", sort_order: 9,
      check_name: "HUD TDC/HCC Limits",
      category: "financial", result: "pass", severity: "warning",
      regulatory_citation: "HUD Notice H-2024-10",
      finding_detail: "Per-unit TDC of $260,000 is within HUD's published TDC limit of $278,000 for the New Orleans MSA (elevator-type, 2025).",
      expected_value: "≤$278,000/unit (NOLA MSA, elevator)", actual_value: "$260,000/unit ✓",
      recommendation: null, created_at: "2025-03-08T10:47:22Z",
    },
    {
      id: "cc-p2-10", proposal_id: "demo-p2", sort_order: 10,
      check_name: "Fair Housing Compliance",
      category: "fair_housing", result: "pass", severity: "informational",
      regulatory_citation: "42 U.S.C. §3604 (Fair Housing Act)",
      finding_detail: "No clustering of smaller units among lower-income households. Unit type distribution appears equitable across all AMI levels.",
      expected_value: "No discriminatory targeting by unit size", actual_value: "Equitable distribution ✓",
      recommendation: null, created_at: "2025-03-08T10:47:22Z",
    },
    {
      id: "cc-p2-11", proposal_id: "demo-p2", sort_order: 11,
      check_name: "Placed-in-Service Timeline",
      category: "section_42", result: "pass", severity: "informational",
      regulatory_citation: "IRC §42(e)(1)",
      finding_detail: "4% bond-financed project. PIS deadline is less constrained than 9% competitive credits. Construction timeline of 22 months is achievable.",
      expected_value: "Achievable construction timeline", actual_value: "22 months projected ✓",
      recommendation: null, created_at: "2025-03-08T10:47:22Z",
    },
  ],

  "demo-p3": [
    {
      id: "cc-p3-01", proposal_id: "demo-p3", sort_order: 1,
      check_name: "HOME Match Requirement",
      category: "home", result: "fail", severity: "critical",
      regulatory_citation: "24 CFR §92.218–220",
      finding_detail: "Project demonstrates only 12.4% match from non-federal sources ($474,000). The HOME program requires a minimum 25% match ($937,500 on $3,750,000 HOME investment). This creates a $463,500 match shortfall that must be resolved before commitment.",
      expected_value: "≥25% match from non-federal sources", actual_value: "12.4% ($474,000)",
      recommendation: "Identify additional non-federal match sources: in-kind contributions, donated land equity, local government direct contribution, or FHLB AHP award. Document and quantify all match sources per 24 CFR §92.220.", created_at: "2025-02-28T16:02:44Z",
    },
    {
      id: "cc-p3-02", proposal_id: "demo-p3", sort_order: 2,
      check_name: "HOME Subsidy Limits",
      category: "home", result: "pass", severity: "critical",
      regulatory_citation: "24 CFR §92.250",
      finding_detail: "HOME investment of $3,750,000 ($78,125/unit) is within HUD's per-unit subsidy limit of $89,400 for the Austin-Round Rock MSA (2025 limits).",
      expected_value: "≤$89,400/unit (Austin MSA, 2025)", actual_value: "$78,125/unit ✓",
      recommendation: null, created_at: "2025-02-28T16:02:44Z",
    },
    {
      id: "cc-p3-03", proposal_id: "demo-p3", sort_order: 3,
      check_name: "HOME Rent Limits",
      category: "home", result: "pass", severity: "critical",
      regulatory_citation: "24 CFR §92.252",
      finding_detail: "Proposed rents are within HOME rent limits for Austin MSA. Low HOME rents for 1BR at $950/mo are below the 30% of 50% AMI ceiling of $1,008/mo. High HOME rents for 2BR at $1,175/mo are within the FMR ceiling.",
      expected_value: "Rents ≤ applicable HOME rent limits", actual_value: "1BR $950 ≤ $1,008; 2BR $1,175 ≤ $1,240 ✓",
      recommendation: null, created_at: "2025-02-28T16:02:44Z",
    },
    {
      id: "cc-p3-04", proposal_id: "demo-p3", sort_order: 4,
      check_name: "HOME Period of Affordability",
      category: "home", result: "pass", severity: "warning",
      regulatory_citation: "24 CFR §92.252(e)",
      finding_detail: "New construction project with 20-year affordability commitment meets the minimum 20-year requirement for new construction under the HOME program.",
      expected_value: "≥20 years (new construction)", actual_value: "20 years ✓",
      recommendation: null, created_at: "2025-02-28T16:02:44Z",
    },
    {
      id: "cc-p3-05", proposal_id: "demo-p3", sort_order: 5,
      check_name: "Debt Service Coverage Ratio",
      category: "financial", result: "fail", severity: "critical",
      regulatory_citation: "HUD Underwriting Guidelines §3.1.3",
      finding_detail: "DSCR of 1.09x falls below the 1.15x minimum threshold required by HUD and most lenders. At this coverage ratio, the project is unlikely to attract conventional financing without restructuring debt terms or increasing operating income.",
      expected_value: "≥1.15x DSCR", actual_value: "1.09x (below minimum)",
      recommendation: "Reduce permanent loan amount, extend loan term to lower debt service, or demonstrate NOI improvement through higher achievable rents or reduced operating expenses. Consider requesting TDHCA's mortgage credit enhancement program.", created_at: "2025-02-28T16:02:44Z",
    },
    {
      id: "cc-p3-06", proposal_id: "demo-p3", sort_order: 6,
      check_name: "Sources and Uses Balance",
      category: "financial", result: "fail", severity: "critical",
      regulatory_citation: "HUD CPD Notice 98-01",
      finding_detail: "Total sources of $9,462,000 are $338,000 short of total uses of $9,800,000 — a 3.4% funding gap. No project may proceed to commitment with an unfunded gap.",
      expected_value: "Sources = Uses (zero gap)", actual_value: "$338,000 gap (3.4% of TDC)",
      recommendation: "Identify additional sources to close the $338,000 gap. Options: increase HOME request (subject to subsidy limits), seek local CDBG or TIRZ gap funding, or reduce project scope/costs.", created_at: "2025-02-28T16:02:44Z",
    },
    {
      id: "cc-p3-07", proposal_id: "demo-p3", sort_order: 7,
      check_name: "Developer Fee Reasonableness",
      category: "financial", result: "pass", severity: "warning",
      regulatory_citation: "HUD CPD Notice 98-01",
      finding_detail: "Developer fee of $1,078,000 represents 11.0% of TDC, within the acceptable range. No deferred developer fee identified.",
      expected_value: "≤15% of TDC", actual_value: "11.0% ($1,078,000) ✓",
      recommendation: null, created_at: "2025-02-28T16:02:44Z",
    },
    {
      id: "cc-p3-08", proposal_id: "demo-p3", sort_order: 8,
      check_name: "Income Targeting Documentation",
      category: "home", result: "needs_review", severity: "warning",
      regulatory_citation: "24 CFR §92.252(b)",
      finding_detail: "All 48 units designated at or below 60% AMI. Verify that the jurisdiction's HOME Action Plan does not impose stricter income targeting requirements, which some grantees adopt.",
      expected_value: "Compliance with jurisdiction HOME Action Plan", actual_value: "60% AMI targeting — verify local requirements",
      recommendation: "Confirm with Austin HOME Program Office that 60% AMI targeting satisfies local consolidated plan priorities.", created_at: "2025-02-28T16:02:44Z",
    },
    {
      id: "cc-p3-09", proposal_id: "demo-p3", sort_order: 9,
      check_name: "Fair Housing Compliance",
      category: "fair_housing", result: "pass", severity: "informational",
      regulatory_citation: "42 U.S.C. §3604; 24 CFR Part 107",
      finding_detail: "No fair housing concerns identified in the unit mix or targeting. Accessibility features for units meet or exceed FHA design standards for new construction.",
      expected_value: "FHA accessibility standards met", actual_value: "Compliant ✓",
      recommendation: null, created_at: "2025-02-28T16:02:44Z",
    },
  ],

  "demo-p5": [
    {
      id: "cc-p5-01", proposal_id: "demo-p5", sort_order: 1,
      check_name: "Income Averaging Election — Average AMI Test",
      category: "section_42", result: "fail", severity: "critical",
      regulatory_citation: "IRC §42(g)(1)(C)",
      finding_detail: "Income average election fails: the proposed AMI designations across all low-income units produce a weighted average of 63.2%, exceeding the 60% maximum required by IRC §42(g)(1)(C). Two units currently designated at 80% AMI must be redesignated to 20% AMI to achieve a compliant average.",
      expected_value: "Weighted average AMI ≤ 60%", actual_value: "63.2% (non-compliant)",
      recommendation: "Redesignate 2 units from 80% AMI to 20% AMI. Recompute weighted average to verify ≤60%. Note that 20% AMI rents are extremely low — confirm the development pro forma can absorb this income loss.", created_at: "2025-02-14T09:30:05Z",
    },
    {
      id: "cc-p5-02", proposal_id: "demo-p5", sort_order: 2,
      check_name: "25% Bond Test (4% Credit Eligibility)",
      category: "section_42", result: "fail", severity: "critical",
      regulatory_citation: "IRC §42(h)(4)(B)",
      finding_detail: "Bond amount of $11,200,000 represents only 40.3% of TDC ($27,800,000). This falls below the 50% threshold required under IRC §42(h)(4)(B) for the project to qualify for 4% credits without a competitive allocation. As structured, no 4% credits can be claimed.",
      expected_value: "Bond ≥ 50% of aggregate basis", actual_value: "40.3% ($11.2M / $27.8M) — FAIL",
      recommendation: "Increase bond amount to at least $13,900,000 (50% of TDC) to satisfy the bond test. This will require additional bond authority from LHC and may require restructuring the permanent financing.", created_at: "2025-02-14T09:30:05Z",
    },
    {
      id: "cc-p5-03", proposal_id: "demo-p5", sort_order: 3,
      check_name: "Eligible Basis — Duplicate Basis Boost",
      category: "section_42", result: "fail", severity: "critical",
      regulatory_citation: "IRC §42(d)(5)(B)",
      finding_detail: "Project claims both QCT and DDA basis boost. Under IRC §42(d)(5)(B), only one 130% boost may apply — a project cannot claim both QCT and DDA enhancement simultaneously. Eligible basis is overstated, inflating the credit amount.",
      expected_value: "Only one of QCT or DDA boost (not both)", actual_value: "Both QCT and DDA claimed — ineligible",
      recommendation: "Remove one designation from the eligible basis calculation. The project should elect whichever single designation (QCT or DDA) provides the most advantageous result and is independently verified.", created_at: "2025-02-14T09:30:05Z",
    },
    {
      id: "cc-p5-04", proposal_id: "demo-p5", sort_order: 4,
      check_name: "Developer Fee Reasonableness",
      category: "financial", result: "fail", severity: "warning",
      regulatory_citation: "LHC 2025 QAP §10.4",
      finding_detail: "Developer fee of $5,587,800 represents 20.1% of TDC — exceeding the LHC 15% standard by 5.1 percentage points. The deferred developer fee of $2,100,000 is unlikely to be repayable given the project's stressed cash flow position.",
      expected_value: "≤15% of TDC ($4,170,000)", actual_value: "20.1% ($5,587,800)",
      recommendation: "Reduce developer fee to ≤15% of TDC. If a higher fee is justified by project complexity, provide a written justification to LHC and demonstrate repayment capacity for the deferred portion.", created_at: "2025-02-14T09:30:05Z",
    },
    {
      id: "cc-p5-05", proposal_id: "demo-p5", sort_order: 5,
      check_name: "Debt Service Coverage Ratio",
      category: "financial", result: "fail", severity: "critical",
      regulatory_citation: "HUD Underwriting Guidelines §3.1.3",
      finding_detail: "DSCR of 1.04x is critically below the 1.15x minimum. At this coverage level, any material increase in operating expenses or vacancy would result in negative cash flow. The project is not financeable in its current form.",
      expected_value: "≥1.15x DSCR", actual_value: "1.04x — critically low",
      recommendation: "Fundamentally restructure the debt. Options include: reducing loan amount, securing a soft second mortgage from LHC, renegotiating interest rate or term, or increasing achievable rents if market data supports.", created_at: "2025-02-14T09:30:05Z",
    },
    {
      id: "cc-p5-06", proposal_id: "demo-p5", sort_order: 6,
      check_name: "Sources and Uses Balance",
      category: "financial", result: "fail", severity: "critical",
      regulatory_citation: "HUD CPD Notice 98-01",
      finding_detail: "Funding gap of $1,240,000 (4.5% of TDC) exists. Total sources as submitted are $26,560,000 against total uses of $27,800,000. This gap is material and must be closed before any commitment.",
      expected_value: "Sources = Uses (zero gap)", actual_value: "$1,240,000 gap (4.5% of TDC)",
      recommendation: "Identify at minimum $1,240,000 in additional sources. Reducing developer fee to LHC limits would partially close the gap. Consider LHC soft loan program or local CDBG funding.", created_at: "2025-02-14T09:30:05Z",
    },
    {
      id: "cc-p5-07", proposal_id: "demo-p5", sort_order: 7,
      check_name: "Tax Credit Equity Pricing",
      category: "financial", result: "fail", severity: "warning",
      regulatory_citation: "Market Standard",
      finding_detail: "Credit equity price of $0.79 per dollar is below the minimum reasonable range of $0.85, indicating that investors have identified significant deal-specific risks. This pricing, combined with the deal's structural issues, suggests limited investor appetite.",
      expected_value: "$0.85–$0.98 per credit dollar", actual_value: "$0.79 — below market floor",
      recommendation: "Resolve all structural issues (bond test, income averaging, developer fee) before re-approaching investors. Corrected structure should achieve market pricing of $0.88–$0.92.", created_at: "2025-02-14T09:30:05Z",
    },
    {
      id: "cc-p5-08", proposal_id: "demo-p5", sort_order: 8,
      check_name: "Placed-in-Service Timeline Risk",
      category: "section_42", result: "needs_review", severity: "warning",
      regulatory_citation: "IRC §42(e)(1)",
      finding_detail: "Zoning status is listed as 'pending variance' as of submission date. If the variance is denied or delayed beyond 90 days, the 2025 bond allocation PIS deadline may be jeopardized.",
      expected_value: "Confirmed zoning by application deadline", actual_value: "Variance pending — timeline risk",
      recommendation: "Provide zoning confirmation or a contingency plan demonstrating the project can meet the PIS deadline under a delayed-zoning scenario.", created_at: "2025-02-14T09:30:05Z",
    },
    {
      id: "cc-p5-09", proposal_id: "demo-p5", sort_order: 9,
      check_name: "Set-Aside Election (Income Average)",
      category: "section_42", result: "pass", severity: "critical",
      regulatory_citation: "IRC §42(g)(1)(C)",
      finding_detail: "Income averaging election was properly made at application. The election mechanism is valid — the issue is the computation of the average AMI (addressed separately).",
      expected_value: "Valid election made at application", actual_value: "Election valid ✓ (computation issue addressed separately)",
      recommendation: null, created_at: "2025-02-14T09:30:05Z",
    },
    {
      id: "cc-p5-10", proposal_id: "demo-p5", sort_order: 10,
      check_name: "Fair Housing Compliance",
      category: "fair_housing", result: "pass", severity: "informational",
      regulatory_citation: "42 U.S.C. §3604",
      finding_detail: "Unit distribution across income levels appears equitable. No discriminatory targeting identified based on available data.",
      expected_value: "Equitable unit distribution", actual_value: "No concerns identified ✓",
      recommendation: null, created_at: "2025-02-14T09:30:05Z",
    },
    {
      id: "cc-p5-11", proposal_id: "demo-p5", sort_order: 11,
      check_name: "Annual Credit Calculation",
      category: "section_42", result: "pass", severity: "warning",
      regulatory_citation: "IRC §42(a)",
      finding_detail: "Stated credit amount of $856,000/year is internally consistent with the stated qualified basis and 4% rate. Note: if the bond test and duplicate boost issues are corrected, the eligible basis and credit amount will need to be recalculated.",
      expected_value: "Internally consistent calculation", actual_value: "$856,000/yr (pending recomputation) ✓",
      recommendation: null, created_at: "2025-02-14T09:30:05Z",
    },
  ],
};

// ---- QAP scores by proposal ID --------------------------------------------

export const DEMO_QAP_SCORES: Record<string, object[]> = {
  "demo-p1": [
    {
      id: "qs-p1-01", proposal_id: "demo-p1", qap_state: "TX", qap_year: 2025, sort_order: 1,
      category_name: "Income Targeting",
      max_points: 22, awarded_points: 18, confidence: 0.95,
      rationale: "8 units at 30% AMI (11.1%) earns 10 base points plus 4 additional points for exceeding 5% threshold. 36 units at 50% AMI earns 4 of the possible 8 points at that tier. Strong deep targeting — competitive for TDHCA 2025.",
      recommendation: "Add 4 more units at 30% AMI to earn maximum points in this category.",
      point_gap: 4,
    },
    {
      id: "qs-p1-02", proposal_id: "demo-p1", qap_state: "TX", qap_year: 2025, sort_order: 2,
      category_name: "Leveraging of Resources",
      max_points: 18, awarded_points: 10, confidence: 0.80,
      rationale: "FHLB AHP award ($600K) and below-market TDHCA MHDB loan identified. No direct financial contribution from local government confirmed in submission. Federal non-LIHTC HUD sources not identified.",
      recommendation: "Secure a direct financial contribution from Harris County or City of Houston (cash, land, or fee waiver) to earn up to 6 additional leveraging points.",
      point_gap: 8,
    },
    {
      id: "qs-p1-03", proposal_id: "demo-p1", qap_state: "TX", qap_year: 2025, sort_order: 3,
      category_name: "Local Political Support",
      max_points: 17, awarded_points: 8, confidence: 0.75,
      rationale: "One letter of support from Harris County Commissioner Court noted. No quantified Community Participation Plan with financial commitment submitted. Missing City Council resolution.",
      recommendation: "Obtain a City of Houston City Council resolution of no objection and develop a Quantified Community Participation Plan with a documented financial commitment from the local subdivision.",
      point_gap: 9,
    },
    {
      id: "qs-p1-04", proposal_id: "demo-p1", qap_state: "TX", qap_year: 2025, sort_order: 4,
      category_name: "Tenant Services",
      max_points: 12, awarded_points: 8, confidence: 0.90,
      rationale: "After-school tutoring (2 pts), employment assistance/job placement (2 pts), and financial literacy programming (2 pts) committed with named provider contract. Health and nutrition services not identified.",
      recommendation: "Add a health/nutrition services commitment (e.g., mobile health clinic partnership or on-site nutrition counseling) with a named provider to earn 2 additional points.",
      point_gap: 4,
    },
    {
      id: "qs-p1-05", proposal_id: "demo-p1", qap_state: "TX", qap_year: 2025, sort_order: 5,
      category_name: "Cost per Square Foot",
      max_points: 12, awarded_points: 9, confidence: 0.70,
      rationale: "Estimated construction cost per square foot of $189 based on TDC and assumed unit size. Falls in TDHCA's second-most efficient tier. Exact square footage data not provided — confidence is moderate.",
      recommendation: "Provide exact gross square footage data. If construction costs can be reduced by 8–10% through value engineering, the project may qualify for the highest efficiency tier.",
      point_gap: 3,
    },
    {
      id: "qs-p1-06", proposal_id: "demo-p1", qap_state: "TX", qap_year: 2025, sort_order: 6,
      category_name: "Proximity to Amenities",
      max_points: 6, awarded_points: 4, confidence: 0.85,
      rationale: "Grocery store within 1 mile (1 pt), medical facility within 3 miles (1 pt), public park within 1 mile (1 pt) confirmed via site analysis. Public transportation is 0.6 miles from site — outside the 0.25-mile threshold for 2 transit points.",
      recommendation: "Verify whether any bus stop, Metro Rail station, or park-and-ride facility is within 0.25 miles. If not, consider negotiating with METRO to add or extend a bus route to the site.",
      point_gap: 2,
    },
    {
      id: "qs-p1-07", proposal_id: "demo-p1", qap_state: "TX", qap_year: 2025, sort_order: 7,
      category_name: "Developer Experience",
      max_points: 10, awarded_points: 7, confidence: 0.90,
      rationale: "Horizon Affordable Housing Partners has 5 completed LIHTC projects placed in service in the last 10 years (4 in TX, 1 in LA). Qualifies for 7 points (5+ projects tier). Would need 10+ projects for maximum points.",
      recommendation: "Document all projects thoroughly. Consider a co-developer with additional completed projects to potentially reach the 10+ project tier.",
      point_gap: 3,
    },
    {
      id: "qs-p1-08", proposal_id: "demo-p1", qap_state: "TX", qap_year: 2025, sort_order: 8,
      category_name: "Readiness to Proceed",
      max_points: 8, awarded_points: 8, confidence: 0.95,
      rationale: "Maximum points awarded: site control confirmed via executed purchase contract, zoning confirmed as multifamily residential, Phase I ESA completed with no RECs, and financing commitments documented.",
      recommendation: null,
      point_gap: 0,
    },
  ],

  "demo-p2": [
    {
      id: "qs-p2-01", proposal_id: "demo-p2", qap_state: "LA", qap_year: 2025, sort_order: 1,
      category_name: "Income Targeting Depth",
      max_points: 20, awarded_points: 16, confidence: 0.95,
      rationale: "Strong income targeting: 18 units at 30% AMI (15%), 54 at 50% AMI (45%), 48 at 60% AMI (40%). Deep targeting at 30% AMI is a competitive differentiator. Loses points only for not reaching 20%+ at 30% AMI.",
      recommendation: "Increasing units at 30% AMI from 15% to 20% of total would likely capture maximum targeting points.",
      point_gap: 4,
    },
    {
      id: "qs-p2-02", proposal_id: "demo-p2", qap_state: "LA", qap_year: 2025, sort_order: 2,
      category_name: "Permanent Supportive Housing",
      max_points: 15, awarded_points: 6, confidence: 0.85,
      rationale: "5 PSH units committed (4.2% of total) with named service provider (Catholic Charities of Archdiocese of New Orleans). Budget line item included. Earns points for sub-5% PSH designation.",
      recommendation: "Increasing PSH commitment to 12+ units (10% of total) would unlock the highest PSH point tier — a significant competitive advantage in the LHC scoring process.",
      point_gap: 9,
    },
    {
      id: "qs-p2-03", proposal_id: "demo-p2", qap_state: "LA", qap_year: 2025, sort_order: 3,
      category_name: "Energy Efficiency and Sustainability",
      max_points: 10, awarded_points: 8, confidence: 0.88,
      rationale: "Enterprise Green Communities 2020 certification committed with third-party verifier identified. Full LEED Silver not specified in application materials.",
      recommendation: "Pursue LEED Silver certification rather than Enterprise Green Communities alone to maximize energy efficiency points.",
      point_gap: 2,
    },
    {
      id: "qs-p2-04", proposal_id: "demo-p2", qap_state: "LA", qap_year: 2025, sort_order: 4,
      category_name: "Community Revitalization",
      max_points: 10, awarded_points: 8, confidence: 0.88,
      rationale: "Located in LHC-designated Community Revitalization Zone in Central City neighborhood. Letter of support from City of New Orleans Planning Director included. Consistent with adopted neighborhood plan.",
      recommendation: "Obtain a formal City Council resolution of support to add the remaining 2 points.",
      point_gap: 2,
    },
    {
      id: "qs-p2-05", proposal_id: "demo-p2", qap_state: "LA", qap_year: 2025, sort_order: 5,
      category_name: "Developer Experience and Compliance History",
      max_points: 15, awarded_points: 12, confidence: 0.92,
      rationale: "Gulf South Community Housing has 7 completed LIHTC projects (5 in LA, 2 in TX), all placed in service within the last 10 years. Clean compliance history — no IRS Form 8823 filings in 10 years.",
      recommendation: "Continue documenting compliance history. Three additional completed projects would achieve maximum experience points.",
      point_gap: 3,
    },
    {
      id: "qs-p2-06", proposal_id: "demo-p2", qap_state: "LA", qap_year: 2025, sort_order: 6,
      category_name: "Cost Efficiency",
      max_points: 10, awarded_points: 7, confidence: 0.80,
      rationale: "Per-unit TDC of $260,000 is at the midpoint of LHC cost guidelines for the New Orleans MSA. Earns middle-tier points.",
      recommendation: "Value engineering to reduce per-unit TDC by $20,000–$30,000 could move the project into the high-efficiency scoring tier.",
      point_gap: 3,
    },
    {
      id: "qs-p2-07", proposal_id: "demo-p2", qap_state: "LA", qap_year: 2025, sort_order: 7,
      category_name: "Leveraging Non-LIHTC Sources",
      max_points: 10, awarded_points: 8, confidence: 0.90,
      rationale: "HUD 221(d)(4) FHA-insured permanent loan and LHC HOME soft loan. Strong leveraging of federal and state sources. Private conventional financing not a primary source.",
      recommendation: "Adding a private conventional loan layer or a local bank CRA loan would capture the remaining 2 leveraging points.",
      point_gap: 2,
    },
    {
      id: "qs-p2-08", proposal_id: "demo-p2", qap_state: "LA", qap_year: 2025, sort_order: 8,
      category_name: "Tenant Services",
      max_points: 10, awarded_points: 3, confidence: 0.82,
      rationale: "Basic tenant services plan submitted without a named provider, dedicated budget line item, or executed MOU. LHC requires a comprehensive plan with committed provider and funding to earn maximum points.",
      recommendation: "Develop and execute a Memorandum of Understanding with a qualified social services provider. Include a dedicated tenant services budget of at minimum $400/unit/year and specify services: case management, employment assistance, and health services.",
      point_gap: 7,
    },
  ],

  "demo-p5": [
    {
      id: "qs-p5-01", proposal_id: "demo-p5", qap_state: "LA", qap_year: 2025, sort_order: 1,
      category_name: "Income Targeting Depth",
      max_points: 20, awarded_points: 4, confidence: 0.85,
      rationale: "Income averaging election is currently non-compliant (average AMI exceeds 60%). Score reflects minimal credit for the stated targeting structure pending compliance correction.",
      recommendation: "Correct the income averaging calculation first. Once compliant, deepen targeting by converting units from 60% AMI to 30–50% AMI to improve score significantly.",
      point_gap: 16,
    },
    {
      id: "qs-p5-02", proposal_id: "demo-p5", qap_state: "LA", qap_year: 2025, sort_order: 2,
      category_name: "Permanent Supportive Housing",
      max_points: 15, awarded_points: 0, confidence: 0.95,
      rationale: "No PSH commitment, service provider, or dedicated budget included in the application. Zero points awarded.",
      recommendation: "Partner with a qualified PSH provider and commit a minimum of 10% of units (9–10 units) to PSH with executed MOU, dedicated service budget, and referral process.",
      point_gap: 15,
    },
    {
      id: "qs-p5-03", proposal_id: "demo-p5", qap_state: "LA", qap_year: 2025, sort_order: 3,
      category_name: "Energy Efficiency and Sustainability",
      max_points: 10, awarded_points: 4, confidence: 0.85,
      rationale: "Energy Star appliances and HVAC committed but no green building certification (Enterprise Green Communities or LEED) identified. Earns only basic energy compliance points.",
      recommendation: "Pursue Enterprise Green Communities 2020 certification as the minimum green building standard. This is achievable at low incremental cost and earns 8 points.",
      point_gap: 6,
    },
    {
      id: "qs-p5-04", proposal_id: "demo-p5", qap_state: "LA", qap_year: 2025, sort_order: 4,
      category_name: "Community Revitalization",
      max_points: 10, awarded_points: 5, confidence: 0.78,
      rationale: "Project located in an area identified in the East Baton Rouge parish comprehensive plan as a development priority. No formal LHC revitalization zone designation confirmed. Letter of support from Parish President included.",
      recommendation: "Seek formal LHC revitalization zone designation for this census tract to earn an additional 3–5 points.",
      point_gap: 5,
    },
    {
      id: "qs-p5-05", proposal_id: "demo-p5", qap_state: "LA", qap_year: 2025, sort_order: 5,
      category_name: "Developer Experience and Compliance History",
      max_points: 15, awarded_points: 5, confidence: 0.88,
      rationale: "Bayou State Development Group has 2 completed LIHTC projects — one received an 8823 for a tenant income file deficiency in 2022. Limited track record and compliance issue reduce score to minimum tier.",
      recommendation: "Bring on an experienced co-developer or co-general partner with a stronger track record and clean compliance history to improve this category.",
      point_gap: 10,
    },
    {
      id: "qs-p5-06", proposal_id: "demo-p5", qap_state: "LA", qap_year: 2025, sort_order: 6,
      category_name: "Cost Efficiency",
      max_points: 10, awarded_points: 3, confidence: 0.82,
      rationale: "Per-unit TDC of $289,583 exceeds LHC published cost guidelines for Baton Rouge MSA. Above-guideline costs earn only minimal efficiency points.",
      recommendation: "Reduce TDC through value engineering. The developer fee reduction (required for compliance) will also improve cost efficiency scoring.",
      point_gap: 7,
    },
    {
      id: "qs-p5-07", proposal_id: "demo-p5", qap_state: "LA", qap_year: 2025, sort_order: 7,
      category_name: "Leveraging Non-LIHTC Sources",
      max_points: 10, awarded_points: 5, confidence: 0.85,
      rationale: "Tax-exempt bond financing is the primary source. No HUD program financing, HOME loan, or local soft financing identified in the sources and uses.",
      recommendation: "Layer LHC HOME funding or seek a local CDBG loan from East Baton Rouge Parish to add a non-LIHTC source and improve leveraging score.",
      point_gap: 5,
    },
    {
      id: "qs-p5-08", proposal_id: "demo-p5", qap_state: "LA", qap_year: 2025, sort_order: 8,
      category_name: "Tenant Services",
      max_points: 10, awarded_points: 5, confidence: 0.80,
      rationale: "Basic tenant services plan with a named provider (Community Health Alliance) but no executed MOU or dedicated budget line item. Earns partial credit for having a plan and named provider.",
      recommendation: "Execute a formal MOU with Community Health Alliance, establish a dedicated tenant services budget of $350+/unit/year, and specify measurable service outcomes.",
      point_gap: 5,
    },
  ],
};
